homework_06/web/models.py
from sqlalchemy import Column, Integer, String

from database import Base


class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    surname = Column(String(50))
    login = Column(String(50), unique=True)
    email = Column(String(120), unique=True)

    def __init__(self, name=None, surname=None, login=None, email=None):
        self.name = name
        self.surname = surname
        self.login = login
        self.email = email

    def __repr__(self):
        return f'<User {self.login!r}>'

homework_06/web/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired, Email


class UserForm(FlaskForm):
    name = StringField('Name: ', validators=[InputRequired()])
    email = StringField('Email: ', validators=[InputRequired(), Email()])
    login = StringField('Login: ', validators=[InputRequired()])
    surname = StringField('Surname: ', validators=[InputRequired()])
    submit = SubmitField('Submit')

homework_06/web/app.py
from flask import Flask, render_template

from users import users_blueprint
from database import init_db, db_session


def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')
    app.register_blueprint(users_blueprint, url_prefix='/users')

    with app.app_context():
        init_db()

    return app


app = create_app()


@app.teardown_appcontext
def shutdown_session(exception=None):
    db_session.remove()


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/about/')
def about():
    return render_template('about.html')

homework_06/web/users/__init__.py
from flask import Blueprint

users_blueprint = Blueprint('users', __name__)

from users import routes

homework_06/web/users/routes.py
from flask import render_template, request, redirect, url_for

from users import users_blueprint
from users.forms import UserForm
from database import db_session
from models import User


@users_blueprint.route('/')
def view():
    users_list = User.query.all()
    return render_template('users/view.html', users_list=users_list)


@users_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            name=form.name.data,
            surname=form.surname.data,
            login=form.login.data,
            email=form.email.data
        )
        db_session.add(user)
        db_session.commit()
        return redirect(url_for('users.view'))
    return render_template('users/add.html', form=form)

homework_06/web/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    <h1>About</h1>
    <p>This is a basic web app on Flask.</p>
{% endblock %}

homework_06/web/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Базовое веб-приложение на Flask с использованием Bootstrap">
    <meta name="author" content="Vladimir Perminov@PaRo44">
    <link rel="icon" href="https://avatars.githubusercontent.com/u/100147032?v=4">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/static/css/styles.css" rel="stylesheet">
    <title>{% block title %}{% endblock %} - Basic App</title>
    {% endblock %}
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="p-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM5.5 4.002V12h1.283V9.164h1.668C10.033 9.164 11 8.08 11 6.586c0-1.482-.955-2.584-2.538-2.584H5.5Zm2.77 4.072c.893 0 1.419-.545 1.419-1.488s-.526-1.482-1.42-1.482H6.778v2.97H8.27Z"/>
      </symbol>
    </svg>
    <header id="page-header" class="container-fluid g-0">
      <nav class="navbar navbar-expand-lg navbar-light mb-4">
        <div class="container-fluid justify-content-start ps-4">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-6 ps-0">
            <li class="nav-item">
              <a href="/" id="app-logo" class="navbar-brand feature-icon d-inline-flex align-items-center justify-content-center me-1">
                <svg class="bi" fill="#87C1FF" width="32px" height="32px"><use xlink:href="#p-circle-fill"></use></svg>
              </a>
            </li>
            <li class="nav-item">
              <a class="ps-3 nav-link {% if request.url_rule.endpoint == 'index' %}active{% endif %}" {% if request.url_rule.endpoint == 'index' %}aria-current="page"{% endif %} href="{{ url_for('index') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.url_rule.endpoint == 'about' %}active{% endif %}" {% if request.url_rule.endpoint == 'about' %}aria-current="page"{% endif %} href="{{ url_for('users.view') }}">View users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.url_rule.endpoint == 'about' %}active{% endif %}" {% if request.url_rule.endpoint == 'about' %}aria-current="page"{% endif %} href="{{ url_for('users.add') }}">Add user</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.url_rule.endpoint == 'about' %}active{% endif %}" {% if request.url_rule.endpoint == 'about' %}aria-current="page"{% endif %} href="{{ url_for('about') }}">About</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main id="page-wrapper" class="container">
      <section id="content">
        <div class="row">
          <div class="col">
            <article id="typography">
              <div>{% block content %}{% endblock %}</div>
            </article>
          </div>
        </div>
      </section>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

homework_06/web/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    <h1>Main page</h1>
{% endblock %}

homework_06/web/templates/users/add.html
{% extends "base.html" %}
{% block title %}Add new user{% endblock %}
{% block content %}
<h1 class="mb-3">Add a New User</h1>
<form method="POST" id="user-form" class="row">
    {{ form.csrf_token }}
    <div class="col-md-2">
        <div class="field">
            <p>
                {{ form.name.label(class_="form-label") }}
                {{ form.name(class_="form-control") }}
            </p>
            {% if form.name.errors %}
                <ul class="errors">
                    {% for error in form.name.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="field">
            <p>
                {{ form.surname.label(class_="form-label") }}
                {{ form.surname(class_="form-control") }}
            </p>
            {% if form.surname.errors %}
                <ul class="errors">
                    {% for error in form.surname.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="field">
            <p>
                {{ form.login.label(class_="form-label") }}
                {{ form.login(class_="form-control") }}
            </p>
            {% if form.login.errors %}
                <ul class="errors">
                    {% for error in form.login.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="field">
            <p>
                {{ form.email.label(class_="form-label") }}
                {{ form.email(class_="form-control") }}
            </p>
            {% if form.email.errors %}
                <ul class="errors">
                    {% for error in form.email.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <p>
            {{ form.submit(class_="btn px-4 btn-primary mt-3") }}
        </p>
    </div>
</form>
{% endblock %}

homework_06/web/templates/users/view.html
{% extends "base.html" %}
{% block title %}View all users{% endblock %}
{% block content %}
<h1 class="mb-4">View all users</h1>
<div class="row row-cols-1 row-cols-md-3" id="user-cards">
{% for user in users_list %}
  <div class="col">
    <div class="card">
      <div class="card-header">
        {{ user.name }} {{ user.surname }}
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ user.login }}</li>
        <li class="list-group-item">{{ user.email }}</li>
      </ul>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}